CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create users table
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL
);

CREATE TABLE IF NOT EXISTS goal
(
    id          UUID DEFAULT gen_random_uuid()       PRIMARY KEY,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    amount      DECIMAL                                 NOT NULL,
    user_id     BIGINT NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS Budgets
(
    id          UUID DEFAULT gen_random_uuid()       PRIMARY KEY,
    name        VARCHAR(255)                            NOT NULL,
    category    VARCHAR(255)                            NOT NULL,
    amount      DECIMAL                                 NOT NULL,
    user_id     BIGINT NOT NULL REFERENCES users (id)
);

-- Create Transactions table
CREATE TABLE IF NOT EXISTS transactions
(
    id          UUID DEFAULT gen_random_uuid()       PRIMARY KEY,
    description VARCHAR(255)                            NOT NULL,
    amount      DECIMAL                                 NOT NULL,
    date        DATE                                    NOT NULL,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    goal_id     UUID REFERENCES goal (id)
);
